// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufakgvgxswpusixoawsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmYWtndmd4c3dwdXNpeG9hd3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyODA3NDQsImV4cCI6MjA3Nzg1Njc0NH0.03t5jTLWMGQ_41Wbhv2bXPn1nQXanWJRBhVs-glWBXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});